# Setup
git config git-ftp.url ftp.vanya05g.net
git config git-ftp.user Vanya05g
git config git-ftp.password VONO05.05

# Upload all files
git ftp init

# Or if the files are already there
git ftp catchup

# Work and deploy
echo "new content" >> index.txt
git commit index.txt -m "Add new content"
git ftp push
# 1 file to sync:
# [1 of 1] Buffered for upload 'index.txt'.
# Uploading ...
# Last deployment changed to 
